name: Test

on: [push]

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    env:
      PIPENV_DEFAULT_PYTHON_VERSION: ${{matrix.python-version}}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: ["MacOS", "Ubuntu", "Windows"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv==2021.11.15
        pipenv sync --dev

    - name: Run Unittest
      run: |
        pipenv run python -m unittest
